### ISSUE TITLE
Crashes with larger files

### ISSUE THREAD

**Issue by shirotech** [Rich-Harris/code-red#41] opened 2020-05-20 20:11 UTC
It seems this package is being used by the svelte compiler, the problem we are facing is when it tries to process files over 66K, it just chokes. Hope you guys can look into this, let me know if more info is required.

https://github.com/AlexxNB/svelte-docs/issues/13

```
[!] (plugin svelte) RangeError: Maximum call stack size exceeded
src/pages/modules/core/changelog.md
RangeError: Maximum call stack size exceeded
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:581:10
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:226:10
    at handle (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:70:17)
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:248:18
    at Array.map (<anonymous>)
    at handle_body (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:247:21)
    at Program (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:318:10)
    at handle (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:70:17)
    at print (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:1413:17)
    at Component.generate (/Volumes/Projects/Projects/docs/node_modules/svelte/src/compiler/compile/Component.ts:316:9)
```

**Comment by Conduitry** [comment] 2020-05-20 20:22
Duplicate of #40.

**Closed by Conduitry** 2020-05-20 20:22 UTC
